### ISSUE TITLE
HttpContextBase: How can we have a dependency on HttpContextBase instead of IHttpContextAccessor?

### ISSUE THREAD

**Issue by mac-bhaird** [Jehoel/AspNetDependencyInjection#12]
Just a quick question, hopefully.

How can we have a constructor dependency on HttpContextBase instead of IHttpContextAccessor?

**Comment by Jehoel** [comment]
Register a custom factory for `HttpContextBase` in your DI controller. The custom factory would then accept `IHttpContextAccessor` and then return the `HttpContextBase` instance.

**Comment by mac-bhaird** [comment]
Note: we tried a factory, but ended up with this message:

MESSAGE: Cannot consume scoped service 'AspNetDependencyInjection.IHttpContextAccessor' from singleton 'App2.HttpContextBaseFactory'.
SOURCE: Microsoft.Extensions.DependencyInjection


`  public class HttpContextBaseFactory : IServiceFactory<HttpContextBase>
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public HttpContextBaseFactory(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public HttpContextBase CreateInstance()
        {
            return _httpContextAccessor.HttpContext;
        }
    }`

**Comment by Jehoel** [comment]
Why are you registering it as a Singleton?

**Comment by mac-bhaird** [comment]
Not intentionally, it looks like this:

            services.AddScopedWithFactory<HttpContextBase, HttpContextBaseFactory>();

**Comment by Jehoel** [comment]
Ah - that's my fault - when I wrote `AddScopedWithFactory` I assumed all factories would be safe as singletons. I'll make a note to revise that in future.

**Comment by mac-bhaird** [comment]
Can I duplicate AddScopedWithFactory and change it a bit? Where is that at? Is there a cleaner way?

**Comment by Jehoel** [comment]
Here, try this:

(From https://github.com/Jehoel/AspNetDependencyInjection/blob/99365a2f11b73d050d8fd60548ae5daabe1b581c/AspNetDependencyInjection/AspNetDependencyInjection.Services/ServiceFactory/IServiceFactory.cs )

```
public static partial class ServiceCollectionExtensions
{
    public static IServiceCollection AddScopedWithScopedFactory<TService,TServiceFactory>( this IServiceCollection services )
        where TService        : class
        where TServiceFactory : class, IServiceFactory<TService>
    {
        return services
            .AddScoped<TServiceFactory>()
            .AddScoped<IServiceFactory<TService>,TServiceFactory>()
            .AddScoped<TService>( implementationFactory: sp => sp.GetRequiredService<TServiceFactory>().CreateInstance() );
		}
	}
```

**Comment by mac-bhaird** [comment]
awesome, looks like it works! Thank you!

**Comment by Jehoel** [comment]
\*bows\*
