### ISSUE TITLE
AddScopedWithScopedFactory: The HttpContextBase has not been set for this Service Scope

### ISSUE THREAD

**Issue by mac-bhaird** [Jehoel/AspNetDependencyInjection#13]
Using the solution from: https://github.com/Jehoel/AspNetDependencyInjection/issues/12 we are intermittently getting the following:

MESSAGE: The HttpContextBase has not been set for this Service Scope.
SOURCE: AspNetDependencyInjection

The error is firing here:

.AddScoped<TService>(implementationFactory: sp => sp.GetRequiredService<TServiceFactory>().CreateInstance());

thoughts?

**Comment by Jehoel** [comment]
Please post the entire exception details (StackTrace, Message, Type - for the root and every child `InnerException`).

I suspect that you're instantiating an class that uses a Scoped Service **outside** of an ASP.NET `HttpContext` request thread (such as in a BackgroundWorker/`HostingEnvironment`,  or `new Thread`). Please post as much code as you can.

**Comment by mac-bhaird** [comment]
You were correct, this has been resolved on our side I believe!
