### ISSUE TITLE
VB sample project

### ISSUE THREAD

**Issue by jrmoreno1** [Jehoel/AspNetDependencyInjection#14]
It would be nice if there was a VB sample project.  I've created one based on the SampleWebApplication.  If you'd take a pull request, let me know.

**Comment by Jehoel** [comment]
Sure, I'll merge it.

**Comment by Jehoel** [comment]
Thank you for submitting it ( https://github.com/Jehoel/AspNetDependencyInjection/pull/16 ). I've done a review and I've requested changes before I merge it.
