### ISSUE TITLE
Mvc unable to resolve controllers not registered as services

### ISSUE THREAD

**Issue by TheJayMann** [Jehoel/AspNetDependencyInjection#27]
I am not sure if this is by design or not (the getting started and sample MVC application appear to suggest that it might not be), but when attempting to get one of my existing MVC projects ported over from a different dependency injection service to instead use this one, I was unable to get controllers to work with dependency injection unless I had added the controllers as services themselves.  It appears this is due to the Mvc package having no path to `ActivatorUtilities.CreateInstance` (or, in this case, `ActivatorUtilities.CreateFactory`).  It is only called by [`RequiredObjectFactoryFactory`](https://github.com/Jehoel/AspNetDependencyInjection/blob/031f8d3dc6d6b5158c0af7a8bff7a8bd87aaa7fe/AspNetDependencyInjection/AspNetDependencyInjection/ObjectFactoryCache.cs#L197), which itself is only used when calling `GetRequiredService`, where Mvc only calls `TryGetService`.

**Comment by Jehoel** [comment]
I've just published version `5.0.0-beta01` which I think fixes this issue - can you verify that at your end?

https://www.nuget.org/packages/Jehoel.AspNetDependencyInjection/5.0.0-beta01

https://www.nuget.org/packages/Jehoel.AspNetDependencyInjection.Mvc/5.0.0-beta01

**Comment by TheJayMann** [comment]
This does not appear to have fixed anything beyond the current 4.0.0 release.  In addition to this not being fixed, it appears that #20 and #21 also have not been included in this beta release.  In fact, following a suspicion, I decided to download the 4.0.0 packages and the 5.0.0-beta01 packages, extracted them, and compared them with KDiff3, and it told me that the DLL and XML Doc files were identical.  Perhaps you didn't build the changes in release mode before packaging them, as, if I'm not mistaken, only release mode build actually copies the output files to the location that the nuget script uses to build the packages.

**Comment by Jehoel** [comment]
@TheJayMann Hmm, that's weird. Hang on...

**Comment by TheJayMann** [comment]
I can confirm that beta2 fixes every issue I've had so far using with my current project.

**Comment by Jehoel** [comment]
I'll publish version 5 now then :)
