### ISSUE TITLE
Getting Started error in provided code for MVC usage

### ISSUE THREAD

**Issue by TheJayMann** [Jehoel/AspNetDependencyInjection#4]
In the sample code provided in the second step of the GettingStarted.md, it states that, to use MVC, invoke the `MvcApplicationDependencyInjection.Configure` method.  However, this appears to resolve to the `ApplicationDependencyInjection.Configure` method, and the correct method to invoke is `MvcApplicationDependencyInjection.ConfigureMvc`.

**Comment by Jehoel** [comment]
This is now fixed and published in version `3.3.0.`. Thank you for the issue report :)
